### ISSUE TITLE
Word cloud for subreddits

### ISSUE THREAD

**Issue by dalyons3** [uc-cfss/viz-shugamoe#3]
Hey,

Just wanted to suggest generating something like a word cloud to reflect a poster's subreddit posting history? Might be helpful for interactivity re: seeing post history and context without being invasive or bogged down.

**Comment by shugamoe** [comment]
I think this would be great, did you mean a wordcloud of the subreddit tiles or a wordcloud of the words in their submissions (or both)?

**Comment by dalyons3** [comment]
Wordcloud of the subreddit tiles. So instead of digging through the post history I just look at the cloud at a glance and a see, "oh this person posted a bunch on r/theDonald and r/asktrumpsupporters". The latter wordcloud would be cool too!

**Comment by shugamoe** [comment]
Ahhh OK, I'll implement both!
